// Code generated by ./internal/cmd/genraymath DO NOT EDIT.

package rl

// MultiplyVector2 - Multiplies a vector by a matrix 2x2
func (m Mat2) MultiplyVector2(vector Vector2) Vector2 {
	return Mat2MultiplyVector2(m, vector)
}

// Transpose - Returns the transpose of a given matrix 2x2
func (m Mat2) Transpose() Mat2 {
	return Mat2Transpose(m)
}

// Add - Add two matrices
func (m Matrix) Add(right Matrix) Matrix {
	return MatrixAdd(m, right)
}

// Decompose - Decompose a transformation matrix into its rotational, translational and scaling components
func (m Matrix) Decompose(translation *Vector3, rotation *Quaternion, scale *Vector3) {
	MatrixDecompose(m, translation, rotation, scale)
}

// Determinant - Compute matrix determinant
func (m Matrix) Determinant() float32 {
	return MatrixDeterminant(m)
}

// Invert - Invert provided matrix
func (m Matrix) Invert() Matrix {
	return MatrixInvert(m)
}

// Multiply - Returns two matrix multiplication
func (m Matrix) Multiply(right Matrix) Matrix {
	return MatrixMultiply(m, right)
}

// Normalize - Normalize provided matrix
func (m Matrix) Normalize() Matrix {
	return MatrixNormalize(m)
}

// Subtract - Subtract two matrices (left - right)
func (m Matrix) Subtract(right Matrix) Matrix {
	return MatrixSubtract(m, right)
}

// ToFloat - Converts Matrix to float32 slice
func (m Matrix) ToFloat() []float32 {
	return MatrixToFloat(m)
}

// ToFloatV - Get float array of matrix data
func (m Matrix) ToFloatV() [16]float32 {
	return MatrixToFloatV(m)
}

// Trace - Returns the trace of the matrix (sum of the values along the diagonal)
func (m Matrix) Trace() float32 {
	return MatrixTrace(m)
}

// Transpose - Transposes provided matrix
func (m Matrix) Transpose() Matrix {
	return MatrixTranspose(m)
}

// Add - Add two quaternions
func (q Quaternion) Add(q2 Quaternion) Quaternion {
	return QuaternionAdd(q, q2)
}

// AddValue - Add quaternion and float value
func (q Quaternion) AddValue(add float32) Quaternion {
	return QuaternionAddValue(q, add)
}

// Divide - Divide two quaternions
func (q Quaternion) Divide(q2 Quaternion) Quaternion {
	return QuaternionDivide(q, q2)
}

// Equals - Check whether two given quaternions are almost equal
func (q Quaternion) Equals(p Quaternion) bool {
	return QuaternionEquals(q, p)
}

// Invert - Invert provided quaternion
func (q Quaternion) Invert() Quaternion {
	return QuaternionInvert(q)
}

// Length - Compute the length of a quaternion
func (q Quaternion) Length() float32 {
	return QuaternionLength(q)
}

// Lerp - Calculate linear interpolation between two quaternions
func (q Quaternion) Lerp(q2 Quaternion, amount float32) Quaternion {
	return QuaternionLerp(q, q2, amount)
}

// Multiply - Calculate two quaternion multiplication
func (q Quaternion) Multiply(q2 Quaternion) Quaternion {
	return QuaternionMultiply(q, q2)
}

// Nlerp - Calculate slerp-optimized interpolation between two quaternions
func (q Quaternion) Nlerp(q2 Quaternion, amount float32) Quaternion {
	return QuaternionNlerp(q, q2, amount)
}

// Normalize - Normalize provided quaternion
func (q Quaternion) Normalize() Quaternion {
	return QuaternionNormalize(q)
}

// Scale - Scale quaternion by float value
func (q Quaternion) Scale(mul float32) Quaternion {
	return QuaternionScale(q, mul)
}

// Slerp - Calculates spherical linear interpolation between two quaternions
func (q Quaternion) Slerp(q2 Quaternion, amount float32) Quaternion {
	return QuaternionSlerp(q, q2, amount)
}

// Subtract - Subtract two quaternions
func (q Quaternion) Subtract(q2 Quaternion) Quaternion {
	return QuaternionSubtract(q, q2)
}

// SubtractValue - Subtract quaternion and float value
func (q Quaternion) SubtractValue(sub float32) Quaternion {
	return QuaternionSubtractValue(q, sub)
}

// ToAxisAngle - Returns the rotation angle and axis for a given quaternion
func (q Quaternion) ToAxisAngle(outAxis *Vector3, outAngle *float32) {
	QuaternionToAxisAngle(q, outAxis, outAngle)
}

// ToEuler - Get the Euler angles equivalent to quaternion (roll, pitch, yaw)
// NOTE: Angles are returned in a Vector3 struct in radians
func (q Quaternion) ToEuler() Vector3 {
	return QuaternionToEuler(q)
}

// ToMatrix - Returns a matrix for a given quaternion
func (q Quaternion) ToMatrix() Matrix {
	return QuaternionToMatrix(q)
}

// Transform - Transform a quaternion given a transformation matrix
func (q Quaternion) Transform(mat Matrix) Quaternion {
	return QuaternionTransform(q, mat)
}

// Add - Add two vectors (v1 + v2)
func (v Vector2) Add(v2 Vector2) Vector2 {
	return Vector2Add(v, v2)
}

// AddValue - Add vector and float value
func (v Vector2) AddValue(add float32) Vector2 {
	return Vector2AddValue(v, add)
}

// Angle - Calculate angle from two vectors in radians
// NOTE: Coordinate system convention: positive X right, positive Y down,
// positive angles appear clockwise, and negative angles appear counterclockwise
func (v Vector2) Angle(v2 Vector2) float32 {
	return Vector2Angle(v, v2)
}

// Clamp - Clamp the components of the vector between min and max values specified by the given vectors
func (v Vector2) Clamp(min Vector2, max Vector2) Vector2 {
	return Vector2Clamp(v, min, max)
}

// ClampValue - Clamp the magnitude of the vector between two min and max values
func (v Vector2) ClampValue(min float32, max float32) Vector2 {
	return Vector2ClampValue(v, min, max)
}

// CrossProduct - Calculate two vectors cross product
func (v Vector2) CrossProduct(v2 Vector2) float32 {
	return Vector2CrossProduct(v, v2)
}

// Distance - Calculate distance between two vectors
func (v Vector2) Distance(v2 Vector2) float32 {
	return Vector2Distance(v, v2)
}

// DistanceSqr - Calculate square distance between two vectors
func (v Vector2) DistanceSqr(v2 Vector2) float32 {
	return Vector2DistanceSqr(v, v2)
}

// Divide - Divide vector by vector
func (v Vector2) Divide(v2 Vector2) Vector2 {
	return Vector2Divide(v, v2)
}

// DotProduct - Calculate two vectors dot product
func (v Vector2) DotProduct(v2 Vector2) float32 {
	return Vector2DotProduct(v, v2)
}

// Equals - Check whether two given vectors are almost equal
func (v Vector2) Equals(q Vector2) bool {
	return Vector2Equals(v, q)
}

// Invert - Invert the given vector
func (v Vector2) Invert() Vector2 {
	return Vector2Invert(v)
}

// Length - Calculate vector length
func (v Vector2) Length() float32 {
	return Vector2Length(v)
}

// LengthSqr - Calculate vector square length
func (v Vector2) LengthSqr() float32 {
	return Vector2LengthSqr(v)
}

// Lerp - Calculate linear interpolation between two vectors
func (v Vector2) Lerp(v2 Vector2, amount float32) Vector2 {
	return Vector2Lerp(v, v2, amount)
}

// LineAngle - Calculate angle defined by a two vectors line
// NOTE: Parameters need to be normalized. Current implementation should be aligned with glm::angle
func (v Vector2) LineAngle(end Vector2) float32 {
	return Vector2LineAngle(v, end)
}

// MoveTowards - Move Vector towards target
func (v Vector2) MoveTowards(target Vector2, maxDistance float32) Vector2 {
	return Vector2MoveTowards(v, target, maxDistance)
}

// Multiply - Multiply vector by vector
func (v Vector2) Multiply(v2 Vector2) Vector2 {
	return Vector2Multiply(v, v2)
}

// Negate - Negate vector
func (v Vector2) Negate() Vector2 {
	return Vector2Negate(v)
}

// Normalize - Normalize provided vector
func (v Vector2) Normalize() Vector2 {
	return Vector2Normalize(v)
}

// Reflect - Calculate reflected vector to normal
func (v Vector2) Reflect(normal Vector2) Vector2 {
	return Vector2Reflect(v, normal)
}

// Rotate - Rotate vector by angle
func (v Vector2) Rotate(angle float32) Vector2 {
	return Vector2Rotate(v, angle)
}

// Scale - Scale vector (multiply by value)
func (v Vector2) Scale(scale float32) Vector2 {
	return Vector2Scale(v, scale)
}

// Subtract - Subtract two vectors (v1 - v2)
func (v Vector2) Subtract(v2 Vector2) Vector2 {
	return Vector2Subtract(v, v2)
}

// SubtractValue - Subtract vector by float value
func (v Vector2) SubtractValue(sub float32) Vector2 {
	return Vector2SubtractValue(v, sub)
}

// Transform - Transforms a Vector2 by a given Matrix
func (v Vector2) Transform(mat Matrix) Vector2 {
	return Vector2Transform(v, mat)
}

// Add - Add two vectors
func (v Vector3) Add(v2 Vector3) Vector3 {
	return Vector3Add(v, v2)
}

// AddValue - Add vector and float value
func (v Vector3) AddValue(add float32) Vector3 {
	return Vector3AddValue(v, add)
}

// Angle - Calculate angle between two vectors
func (v Vector3) Angle(v2 Vector3) float32 {
	return Vector3Angle(v, v2)
}

// Barycenter - Barycenter coords for p in triangle abc
func (v Vector3) Barycenter(a, b, c Vector3) Vector3 {
	return Vector3Barycenter(v, a, b, c)
}

// Clamp - Clamp the components of the vector between min and max values specified by the given vectors
func (v Vector3) Clamp(min Vector3, max Vector3) Vector3 {
	return Vector3Clamp(v, min, max)
}

// ClampValue - Clamp the magnitude of the vector between two values
func (v Vector3) ClampValue(min float32, max float32) Vector3 {
	return Vector3ClampValue(v, min, max)
}

// CrossProduct - Calculate two vectors cross product
func (v Vector3) CrossProduct(v2 Vector3) Vector3 {
	return Vector3CrossProduct(v, v2)
}

// Distance - Calculate distance between two vectors
func (v Vector3) Distance(v2 Vector3) float32 {
	return Vector3Distance(v, v2)
}

// DistanceSqr - Calculate square distance between two vectors
func (v Vector3) DistanceSqr(v2 Vector3) float32 {
	return Vector3DistanceSqr(v, v2)
}

// Divide - Divide vector by vector
func (v Vector3) Divide(v2 Vector3) Vector3 {
	return Vector3Divide(v, v2)
}

// DotProduct - Calculate two vectors dot product
func (v Vector3) DotProduct(v2 Vector3) float32 {
	return Vector3DotProduct(v, v2)
}

// Equals - Check whether two given vectors are almost equal
func (v Vector3) Equals(q Vector3) bool {
	return Vector3Equals(v, q)
}

// Invert - Invert the given vector
func (v Vector3) Invert() Vector3 {
	return Vector3Invert(v)
}

// Length - Calculate vector length
func (v Vector3) Length() float32 {
	return Vector3Length(v)
}

// LengthSqr - Calculate vector square length
func (v Vector3) LengthSqr() float32 {
	return Vector3LengthSqr(v)
}

// Lerp - Calculate linear interpolation between two vectors
func (v Vector3) Lerp(v2 Vector3, amount float32) Vector3 {
	return Vector3Lerp(v, v2, amount)
}

// Max - Return max value for each pair of components
func (v Vector3) Max(vec2 Vector3) Vector3 {
	return Vector3Max(v, vec2)
}

// Min - Return min value for each pair of components
func (v Vector3) Min(vec2 Vector3) Vector3 {
	return Vector3Min(v, vec2)
}

// Multiply - Multiply vector by vector
func (v Vector3) Multiply(v2 Vector3) Vector3 {
	return Vector3Multiply(v, v2)
}

// Negate - Negate provided vector (invert direction)
func (v Vector3) Negate() Vector3 {
	return Vector3Negate(v)
}

// Normalize - Normalize provided vector
func (v Vector3) Normalize() Vector3 {
	return Vector3Normalize(v)
}

// Perpendicular - Calculate one vector perpendicular vector
func (v Vector3) Perpendicular() Vector3 {
	return Vector3Perpendicular(v)
}

// Project - Calculate the projection of the vector v1 on to v2
func (v Vector3) Project(v2 Vector3) Vector3 {
	return Vector3Project(v, v2)
}

// Reflect - Calculate reflected vector to normal
func (v Vector3) Reflect(normal Vector3) Vector3 {
	return Vector3Reflect(v, normal)
}

// Refract - Compute the direction of a refracted ray
//
// v: normalized direction of the incoming ray
// n: normalized normal vector of the interface of two optical media
// r: ratio of the refractive index of the medium from where the ray comes to the refractive index of the medium on the other side of the surface
func (v Vector3) Refract(n Vector3, r float32) Vector3 {
	return Vector3Refract(v, n, r)
}

// Reject - Calculate the rejection of the vector v1 on to v2
func (v Vector3) Reject(v2 Vector3) Vector3 {
	return Vector3Reject(v, v2)
}

// RotateByAxisAngle - Rotates a vector around an axis
func (v Vector3) RotateByAxisAngle(axis Vector3, angle float32) Vector3 {
	return Vector3RotateByAxisAngle(v, axis, angle)
}

// RotateByQuaternion - Transform a vector by quaternion rotation
func (v Vector3) RotateByQuaternion(q Quaternion) Vector3 {
	return Vector3RotateByQuaternion(v, q)
}

// Scale - Scale provided vector
func (v Vector3) Scale(scale float32) Vector3 {
	return Vector3Scale(v, scale)
}

// Subtract - Subtract two vectors
func (v Vector3) Subtract(v2 Vector3) Vector3 {
	return Vector3Subtract(v, v2)
}

// SubtractValue - Subtract vector by float value
func (v Vector3) SubtractValue(sub float32) Vector3 {
	return Vector3SubtractValue(v, sub)
}

// ToFloat - Converts Vector3 to float32 slice
func (v Vector3) ToFloat() []float32 {
	return Vector3ToFloat(v)
}

// ToFloatV - Get Vector3 as float array
func (v Vector3) ToFloatV() [3]float32 {
	return Vector3ToFloatV(v)
}

// Transform - Transforms a Vector3 by a given Matrix
func (v Vector3) Transform(mat Matrix) Vector3 {
	return Vector3Transform(v, mat)
}

// Unproject - Projects a Vector3 from screen space into object space
// NOTE: We are avoiding calling other raymath functions despite available
func (v Vector3) Unproject(projection Matrix, view Matrix) Vector3 {
	return Vector3Unproject(v, projection, view)
}
